language: python
python:
    - '2.7'
    - '3.3'
    - 'pypy'
env:
    global:
        - APIKEY=MTI2Njc1RDNENEJDOUU5QzVBMTBEQjJDMTdDQUNFOTI=
script: python setup.py run_tests -k $(echo $APIKEY|base64 -d)
notifications:
    email:
        on_success: never
        on_failure: change
    irc:
        channels:
            - "chat.freenode.net#optf2"
        template:
            - "%{repository}/%{branch}#%{commit} by %{author}: %{message} - %{build_url}"
sudo: false
