language: python
python:
    - '2.7'
    - '3.3'
env:
    global:
        - APIKEY=NkExMzEzRDYzQ0EyRTA5NEJCQTJDMUY1N0IwNDk4QkQ=
script: python setup.py run_tests -k $(echo $APIKEY|base64 -d)
notifications:
    email:
        on_success: never
        on_failure: always
    irc:
        channels:
            - "chat.freenode.net#optf2"
        template:
            - "%{repository}/%{branch}#%{commit} by %{author}: %{message} - %{build_url}"
